### ISSUE TITLE
Ebms, AS2 plugin issues | Jentrata setup

### ISSUE THREAD

**Issue by mahendrav4u** [jentrata/jentrata-msh#16]
Hi All,

We have just started exploring jentrata and done with the setup/installation of jentrata-msh by following the instructions published on github. We have successfully installed jentrata and able to hit the URL and also login is successful.

But after login, we could see that AS2 & EBMS plugins are having error in the home page (but no errors in the logs when we click them). Can someone help us getting them up & running. 

Attaching the screen shots & loggers for your reference. As we are new to jentrata, any pointers will be of great help.

[Ebms and As2 plugin errors.docx](https://github.com/jentrata/jentrata-msh/files/134695/Ebms.and.As2.plugin.errors.docx)

Regards,
Mahendar

**Comment by aaronwalker** [comment]
Hi,

Am happy to take at look at your errors but can you please attach the error directly to this issue and not as a word doc.

Can you provide the contents of corvus.log and ebms.log

cheers

Aaron

**Comment by mahendrav4u** [comment]
Hi Aaron,

Attaching the complete jentrata + tomcat logs as zip. Please check.

[jentrata-logs.zip](https://github.com/jentrata/jentrata-msh/files/137805/jentrata-logs.zip)
[tomcat-logs.zip](https://github.com/jentrata/jentrata-msh/files/137807/tomcat-logs.zip)

Also, as we are new to jentrata, can you help us with '**Hello World!**' kind of approach using Jentrata.

Thanks for your help.

Regards,
Mahendar

**Comment by aaronwalker** [comment]
You've got a couple of issues...

Have you setup postgres correctly as I can see this exception in the ebms logs
```
2016-02-19 21:50:41 [Thread-15   ] <ERROR> <cecid.ebms.spa> <Error in collecting message from outbox>
hk.hku.cecid.piazza.commons.dao.DAOException: Unable to begin transaction
	by org.postgresql.util.PSQLException: FATAL: Ident authentication failed for user "corvus"
	at hk.hku.cecid.piazza.commons.dao.ds.DataSourceTransaction.begin(DataSourceTransaction.java:96)
	at hk.hku.cecid.piazza.commons.dao.ds.DataSourceProcess.start(DataSourceProcess.java:84)
	at hk.hku.cecid.piazza.commons.dao.ds.DataSourceDAO.executeQuery(DataSourceDAO.java:437)
	at hk.hku.cecid.piazza.commons.dao.ds.DataSourceDAO.executeQuery(DataSourceDAO.java:416)
	at hk.hku.cecid.piazza.commons.dao.ds.DataSourceDAO.find(DataSourceDAO.java:348)
	at hk.hku.cecid.ebms.spa.dao.MessageDataSourceDAO.findOutboxProcessingMessagesByTimestamp(MessageDataSourceDAO.java:131)
	at hk.hku.cecid.ebms.spa.task.OutboxCollector.getTaskList(OutboxCollector.java:48)
	at hk.hku.cecid.piazza.commons.module.ActiveTaskModule.execute(ActiveTaskModule.java:137)
	at hk.hku.cecid.piazza.commons.module.ActiveModule.run(ActiveModule.java:213)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: FATAL: Ident authentication failed for user "corvus"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:291)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
```
Did you create the postgres database for jentrata with a corvus user as per the README?

Also do you already have an activemq running. looks like you've already got something binding to port 61616

corvus.log
```
hk.hku.cecid.piazza.commons.spa.PluginException: Error in processing activation by handler: org.jentrata.spa.jms.JMSProcessor
	by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize module group 'JMS'
	by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to load modules
	by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'jms-broker'
	by java.io.IOException: Failed to bind to server socket: tcp://localhost:61616?useJmx=true&broker.persistent=false due to: java.net.BindException: Address already in use
	by java.net.BindException: Address already in use
	at hk.hku.cecid.piazza.commons.spa.Plugin.activate(Plugin.java:152)
	at hk.hku.cecid.piazza.commons.spa.PluginRegistry.activatePlugins(PluginRegistry.java:307)
	at hk.hku.cecid.piazza.commons.spa.PluginRegistry.activate(PluginRegistry.java:281)
	at hk.hku.cecid.piazza.corvus.core.Kernel.<init>(Kernel.java:105)
```

**Comment by mahendrav4u** [comment]
Hi Aaron,

Yes, we have done the postgressql setu qas per the README instructions.

I could see that jentrata itself is owning this port number. Below is some trouble shooting for the same.

**-bash-4.1#
-bash-4.1# netstat -tulpn | grep 61616
tcp        0      0 127.0.0.1:61616             0.0.0.0:*                   LISTEN      48701/java

-bash-4.1#
-bash-4.1# fuser 61616/tcp
61616/tcp:           48701
-bash-4.1#
-bash-4.1#
-bash-4.1# ps -ef | grep 48701
root     32830 16500  0 16:57 pts/0    00:00:00 grep 48701
omot1    48701     1 11 Feb19 ?        08:01:51 /data/OMOT/Jentrata/jdk1.7.0_72/bin/java -Djava.util.logging.config.file=/data/OMOT/Jentrata/apache-tomcat-6.0.43/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms1024m -Xmx1024m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=2601 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcorvus.home=/data/OMOT/Jentrata/jentrata-msh-2.x-SNAPSHOT-tomcat-new -Djava.endorsed.dirs=/data/OMOT/Jentrata/apache-tomcat-6.0.43/endorsed -classpath /data/OMOT/Jentrata/apache-tomcat-6.0.43/bin/bootstrap.jar -Dcatalina.base=/data/OMOT/Jentrata/apache-tomcat-6.0.43 -Dcatalina.home=/data/OMOT/Jentrata/apache-tomcat-6.0.43 -Djava.io.tmpdir=/data/OMOT/Jentrata/apache-tomcat-6.0.43/temp org.apache.catalina.startup.Bootstrap start
-bash-4.1#
**
