### ISSUE TITLE
DB connectivity issue

### ISSUE THREAD

**Issue by telstrajhinjer** [jentrata/jentrata-msh#52]
@aaronwalker we are facing db connectivity issue from jentrata. but if we do telnet to our db, we are able to connect.

Below are the logs: if you please look and help that will be great.

2018-10-11 05:12:38 [-startStop-2] <INFO > <Plugin registry (/home/ec2-user/jentrata-msh-master/Dist/target/jentrata-msh-tomcat/plugins) initialized successfully.>
2018-10-11 05:12:38 [-startStop-2] <ERROR> <Error in activating plugin: hk.hku.cecid.ebms>
hk.hku.cecid.piazza.commons.spa.PluginException: Error in processing activation by handler: hk.hku.cecid.ebms.spa.EbmsProcessor
        by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize module group 'Ebms'
        by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to load modules
        by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'System DAO Factory'
        by hk.hku.cecid.piazza.commons.dao.DAOException: Cannot initialize SimpleDSDAOFactory!
        by hk.hku.cecid.piazza.commons.dao.DAOException: Invalid parameter for SimpleDSDAOFactory.
        at hk.hku.cecid.piazza.commons.spa.Plugin.activate(Plugin.java:152)
        at hk.hku.cecid.piazza.commons.spa.PluginRegistry.activatePlugins(PluginRegistry.java:307)
        at hk.hku.cecid.piazza.commons.spa.PluginRegistry.activate(PluginRegistry.java:281)
        at hk.hku.cecid.piazza.corvus.core.Kernel.<init>(Kernel.java:105)
        at hk.hku.cecid.piazza.corvus.core.Kernel.<clinit>(Kernel.java:32)
        at hk.hku.cecid.piazza.corvus.core.servlet.StartupServlet.init(StartupServlet.java:54)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5409)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5707)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1017)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:993)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2039)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize module group 'Ebms'
        by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to load modules
        by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'System DAO Factory'
        by hk.hku.cecid.piazza.commons.dao.DAOException: Cannot initialize SimpleDSDAOFactory!
        by hk.hku.cecid.piazza.commons.dao.DAOException: Invalid parameter for SimpleDSDAOFactory.
        at hk.hku.cecid.piazza.commons.module.ModuleGroup.<init>(ModuleGroup.java:92)
        at hk.hku.cecid.ebms.spa.EbmsProcessor.processActivation(EbmsProcessor.java:56)
        at hk.hku.cecid.piazza.commons.spa.Plugin.activate(Plugin.java:149)
        ... 21 more
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to load modules
        by hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'System DAO Factory'
        by hk.hku.cecid.piazza.commons.dao.DAOException: Cannot initialize SimpleDSDAOFactory!
        by hk.hku.cecid.piazza.commons.dao.DAOException: Invalid parameter for SimpleDSDAOFactory.
        at hk.hku.cecid.piazza.commons.module.ModuleGroup.loadModules(ModuleGroup.java:130)
        at hk.hku.cecid.piazza.commons.module.ModuleGroup.<init>(ModuleGroup.java:89)
        ... 23 more
Caused by: hk.hku.cecid.piazza.commons.module.ModuleException: Unable to initialize component 'System DAO Factory'
        by hk.hku.cecid.piazza.commons.dao.DAOException: Cannot initialize SimpleDSDAOFactory!
        by hk.hku.cecid.piazza.commons.dao.DAOException: Invalid parameter for SimpleDSDAOFactory.
        at hk.hku.cecid.piazza.commons.module.Module.initComponents(Module.java:189)
        at hk.hku.cecid.piazza.commons.module.Module.init(Module.java:134)
        at hk.hku.cecid.piazza.commons.module.ModuleGroup.loadModules(ModuleGroup.java:112)
        ... 24 more

**Comment by telstrajhinjer** [comment]
@aaronwalker Yes, I can confirm that I am able to connect using same credentials, I am using mysql.

One more question: I want Jentrata to forward the request received to my downstream endpoint. Where I can configure that in jentrata. I have tried setting up in partnership table but it's then just forwarding acknowledgement instead of the ebxml received. My team is looking into this but we are unable to find the solution. For more details below is the explanation:
Jentrata receives the ebxml from other gateway>> Jentrata send back the acknoldgement to the origin from where it received the ebxml>> till this everything is as expected. Going forward, I want to receive that ebxml into my downstream.
Jentrata should forward received ebxml to >>> downstream endpoint for processing. this area is not working as of now. If you can explain in details for settings/configurations then I'll be able to configure and resolve.
Thanks in advance.
