### ISSUE TITLE
Soap Error while hitting ebms/sender

### ISSUE THREAD

**Issue by telstrajhinjer** [jentrata/jentrata-msh#53]
@aaronwalker I managed to resolve my other issues. Thanks for your help. But, Now I am on my last step to send the response back from downsteam. But while I am hitting ebms/sender, I am getting below error.

hk.hku.cecid.piazza.commons.soap.SOAPFaultException: Invalid SOAP message: Unable to internalize message
        by com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Unable to internalize message
        by com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: java.lang.Exception: Missing Start Boundary, or boundary does not start on a new line
        by java.lang.Exception: Missing Start Boundary, or boundary does not start on a new line
        at hk.hku.cecid.piazza.commons.soap.SOAPHttpAdaptor.processRequest(SOAPHttpAdaptor.java:123)
        at hk.hku.cecid.piazza.commons.servlet.http.HttpDispatcher.processRequest(HttpDispatcher.java:126)
        at hk.hku.cecid.piazza.commons.servlet.http.HttpDispatcher.doPost(HttpDispatcher.java:277)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1136)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Unable to internalize message
        at com.sun.xml.internal.messaging.saaj.soap.MessageImpl.init(MessageImpl.java:521)
        at com.sun.xml.internal.messaging.saaj.soap.MessageImpl.<init>(MessageImpl.java:301)
        at com.sun.xml.internal.messaging.saaj.soap.ver1_1.Message1_1Impl.<init>(Message1_1Impl.java:65)
        at com.sun.xml.internal.messaging.saaj.soap.ver1_1.SOAPMessageFactory1_1Impl.createMessage(SOAPMessageFactory1_1Impl.java:59)
        at hk.hku.cecid.piazza.commons.soap.SOAPHttpAdaptor.processRequest(SOAPHttpAdaptor.java:118)
        ... 24 more
Caused by: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: java.lang.Exception: Missing Start Boundary, or boundary does not start on a new line
        at com.sun.xml.internal.messaging.saaj.soap.MessageImpl.init(MessageImpl.java:484)
        ... 28 more
Caused by: java.lang.Exception: Missing Start Boundary, or boundary does not start on a new line
        at com.sun.xml.internal.messaging.saaj.packaging.mime.internet.BMMimeMultipart.getNextPart(BMMimeMultipart.java:240)
        at com.sun.xml.internal.messaging.saaj.soap.MessageImpl.init(MessageImpl.java:473)
        ... 28 more
2018-10-15 03:32:32 [-8080-exec-1] <DEBUG> <Request#2080596274:/ebms/sender@10.61.70.211 had been processed successfully for 4 ms>

**Comment by aaronwalker** [comment]
@telstrajhinjer looks like your not sending a valid soap with attachments message to the sender web service. The payload you want to send needs to be sent to the sender web service as am  attachment (https://www.w3.org/TR/SOAP-attachments) if your using SOAP UI to test take a look at https://www.soapui.org/docs/soap-and-wsdl/attachments.html
